import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { Footer } from "./components/Footer";
import { LoanModalProvider } from "@/components/LoanModalProvider";


const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Infinity Loans",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="bg-white text-gray-900" suppressHydrationWarning>
            <body
                className={`${geistSans.variable} ${geistMono.variable} bg-white antialiased`}
                suppressHydrationWarning
            >
                <LoanModalProvider>
                    <Navbar />
                    {children}
                    <Footer />
                </LoanModalProvider>
            </body>
        </html>
    );
}
